name       : python-torchvision
version    : 0.2.2
release    : 6
source     :
    - https://github.com/pytorch/vision/archive/v0.2.2.tar.gz : 9572c557fe8be1946c76f9fe21ddd0ffd8de487e8d0abc5008d7f58f76acd1b3
license    : BSD-3-Clause
component  : programming.python
summary    : Datasets, Transforms and Models specific to Computer Vision
description: |
    The torchvision package consists of popular datasets, model architectures, and common image transformations for computer vision.
rundeps    :
    - numpy
    - python-pillow
    - python-six
    - python-tqdm
    - pytorch
build      : |
    %python3_setup
install    : |
    %python3_install
