name       : python-torchvision
version    : 0.12.0
release    : 7
source     :
    - https://github.com/pytorch/vision/archive/refs/tags/v0.12.0.tar.gz : 99e6d3d304184895ff4f6152e2d2ec1cbec89b3e057d9c940ae0125546b04e91
license    : BSD-3-Clause
component  : programming.python
summary    : Datasets, Transforms and Models specific to Computer Vision
description: |
    The torchvision package consists of popular datasets, model architectures, and common image transformations for computer vision.
builddeps  :
    - pkgconfig(libavformat)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pytorch
    - libtorch-devel
rundeps    :
    - numpy
    - python-pillow
    - python-six
    - python-tqdm
    - pytorch
environment: |
    export MAX_JOBS=%YJOBS%
build      : |
    %python3_setup
install    : |
    %python3_install
